# Generated by Django 4.2.3 on 2023-07-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='EngineMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='FailureJuncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineSerialNumber', models.CharField(max_length=32)),
                ('engineSerialNumber', models.CharField(max_length=32)),
                ('transmissionSerialNumber', models.CharField(max_length=32)),
                ('drivingBridgeSerialNumber', models.CharField(max_length=32)),
                ('controlledBridgeSerialNumber', models.CharField(max_length=32)),
                ('contract', models.CharField(max_length=64)),
                ('shipDate', models.DateField()),
                ('consignee', models.CharField(max_length=64)),
                ('deliveryAddress', models.CharField(max_length=128)),
                ('picking', models.CharField(max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.client')),
                ('controlledBridgeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.controlledbridgemodel')),
                ('drivingBridgeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.drivingbridgemodel')),
                ('engineMake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.enginemake')),
                ('equipmentModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.equipmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceCompanyUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('failureDescription', models.CharField(max_length=1024)),
                ('spareParts', models.CharField(max_length=1024)),
                ('recoveryDate', models.DateField()),
                ('equipmentDowntime', models.IntegerField(blank=True, editable=False, null=True)),
                ('failureJuncture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.failurejuncture')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.machine')),
                ('recoveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.recoverymethod')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('workOrder', models.CharField(max_length=32)),
                ('workOrderDate', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.machine')),
                ('maintenanceOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.maintenanceorganization')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.maintenancetype')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.transmissionmodel'),
        ),
    ]
