# Generated by Django 4.2.3 on 2023-07-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silant_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='controlledbridgemodel',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='drivingbridgemodel',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='enginemake',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателя'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
        migrations.AlterModelOptions(
            name='failurejuncture',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машиниы'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Тех. Обслуживание', 'verbose_name_plural': 'Тех. Обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceorganization',
            options={'verbose_name': 'Организация, проводившая ТО', 'verbose_name_plural': 'Организации, проводившие ТО'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AlterField(
            model_name='controlledbridgemodel',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='controlledbridgemodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='drivingbridgemodel',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drivingbridgemodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='enginemake',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='enginemake',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='failurejuncture',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='failurejuncture',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.CharField(max_length=64, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='contract',
            field=models.CharField(max_length=64, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='controlledBridgeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.controlledbridgemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='controlledBridgeSerialNumber',
            field=models.CharField(max_length=32, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='deliveryAddress',
            field=models.CharField(max_length=128, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drivingBridgeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.drivingbridgemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drivingBridgeSerialNumber',
            field=models.CharField(max_length=32, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engineMake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.enginemake', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engineSerialNumber',
            field=models.CharField(max_length=32, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipmentModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.equipmentmodel', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineSerialNumber',
            field=models.CharField(max_length=32, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='picking',
            field=models.CharField(max_length=1024, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipDate',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmissionSerialNumber',
            field=models.CharField(max_length=32, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceOrganization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.maintenanceorganization', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operatingTime',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.maintenancetype', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='workOrder',
            field=models.CharField(max_length=32, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='workOrderDate',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenanceorganization',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='maintenanceorganization',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='equipmentDowntime',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failureDate',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failureDescription',
            field=models.CharField(max_length=1024, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failureJuncture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.failurejuncture', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='operatingTime',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='recoveryDate',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='recoveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='spareParts',
            field=models.CharField(max_length=1024, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
