# Generated by Django 4.2.3 on 2023-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_backend', '0002_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledbridgemodel',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='drivingbridgemodel',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='enginemake',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='failurejuncture',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='controlledBridgeSerialNumber',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drivingBridgeSerialNumber',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engineSerialNumber',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineSerialNumber',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmissionSerialNumber',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenanceorganization',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
